### ISSUE TITLE
Custom design for Tutorials overview page

### ISSUE THREAD

**Issue by gohai** [processing/processing-pi-website#13]
Thinking that some tiles with some subtle interaction on hover could be nice for this.

I'll look some more, but I came across e.g.:
https://codepen.io/chrisgrabinski/pen/gpqtc (the first one on the top left looks appealing to me, the rest is a bit too gimmicky IMHO)

Food for thought after the first tutorial!

**Comment by msurguy** [comment]
@gohai I've created a test setup for this feature in this branch: https://github.com/processing/processing-pi-website/tree/feature-tutorial-grid

Here's the example of how it looks like on desktop:
<img width="1119" alt="screen shot 2018-08-02 at 11 15 25 am" src="https://user-images.githubusercontent.com/585833/43602712-9a03e610-9645-11e8-9157-633fcb3fa063.png">

Let me know if this is what you were imagining or along those lines? 

The gist of this feature is in _tutorials-list.scss file if you want to play with colors and paddings and other details.

**Comment by gohai** [comment]
@msurguy Looks fantastic. Is this ready for merging?

**Comment by msurguy** [comment]
@gohai almost ready. I wanted to show this to you before I dig in too deep. Now I have to come up with a way of how to get the individual tutorial info and populate the list, should be done today!

**Comment by msurguy** [comment]
@gohai the PR is now ready to go. We need to decide what kind of images (photos vs sketch vs something else) we want to use for the thumbnails. The aspect ratio should be 16x9.

**Comment by gohai** [comment]
Done! Congrats!
