### ISSUE TITLE
Improve TOC indentation

### ISSUE THREAD

**Issue by gohai** [processing/processing-pi-website#19]
I believe this would benefit from a shallower indentation - what you think?

<img width="337" alt="screen shot 2018-07-09 at 10 27 30 am" src="https://user-images.githubusercontent.com/4945451/42466109-d4367d48-8362-11e8-8bc9-86eaa7ccc93a.png">

**Comment by gohai** [comment]
(shallower meaning less pixels to the right.. not less levels of indentation in the text!)

**Comment by msurguy** [comment]
@gohai Is this better? Fix is in https://github.com/processing/processing-pi-website/pull/20

<img width="1060" alt="screen shot 2018-07-09 at 8 32 51 pm" src="https://user-images.githubusercontent.com/585833/42487818-8da6e5ac-83b7-11e8-85e5-135376775f14.png">

**Comment by gohai** [comment]
It is - thanks!
