### ISSUE TITLE
Design: Article layout

### ISSUE THREAD

**Issue by gohai** [processing/processing-pi-website#2]
The different sections would benefit from some breathing room before/after. It might also be worth limiting the (maximum-) width of the text in paragraphs. Right now the text will go as wide as the container is, but I believe it's best not to go above 90 characters per line for readability.

<hr>

<img width="966" alt="screen shot 2018-05-30 at 10 36 12 am" src="https://user-images.githubusercontent.com/4945451/40737387-71754ebe-63f5-11e8-8c53-471b5e14216b.png">

**Comment by msurguy** [comment]
@gohai addressed via https://github.com/processing/processing-pi-website/pull/6

**Comment by msurguy** [comment]
@gohai I've addressed some of the issues you raised in https://github.com/processing/processing-pi-website/pull/8 and in https://github.com/processing/processing-pi-website/pull/7

The video elements lacked bottom margin which reduced the spacing between the header elements so I added the bottom margin to video elements. 

If you feel like other elements need more room, please let me know!

**Comment by gohai** [comment]
Believe this would still want more breathing room vertically...

Attaching two examples below - perhaps a CSS selector for headings that are not the first child, which pushes them down? Or just more space before and after paragraphs in general?

Notice how the "Tar-balls" heading is closer to the line of code above, than the line of code is to the previous paragraph it belongs to? The block "A first Processing sketch" is almost equally tucked between those two image blocks, whereas only image further down relates to it.

<img width="1188" alt="screen shot 2018-06-14 at 4 28 49 pm" src="https://user-images.githubusercontent.com/4945451/41443220-697ebe78-6ff0-11e8-8e15-4e2c9dde0959.png">
<img width="830" alt="screen shot 2018-06-14 at 4 29 11 pm" src="https://user-images.githubusercontent.com/4945451/41443221-699d7ab6-6ff0-11e8-813f-09b6efea0029.png">

**Comment by msurguy** [comment]
These issues have been addressed in previous PRs, closing
