### ISSUE TITLE
edit this repo!

### ISSUE THREAD

**Issue by fabsenet** [processing/processing-pi-website#25]
Hi!

i would suggest you to edit this repo and provide the actual url of the website so people can simply click on it. It could be well invested 30seconds :-)

It usually appears here (yellow rectangle):

![image](https://user-images.githubusercontent.com/2065705/43395152-5e33640c-93fd-11e8-8e8d-57757b23f943.png)

**Comment by msurguy** [comment]
@gohai could you please take care of that? I don't have the permission for that :)

@fabsenet thanks for reporting this!
