### ISSUE TITLE
Design: Make image download more obvious

### ISSUE THREAD

**Issue by gohai** [processing/processing-pi-website#3]
The initial thing users will be looking for on the site will be the image file to download and put on the microSD card. Right now the Download link is pretty much unassuming - perhaps it would be worth framing it, or otherwise providing some focus.

We could also offer more information at this point, e.g.:

- file size (already shown)
- release date
- version
- link to a file with release notes

<hr>

**Current**

<img width="508" alt="screen shot 2018-05-30 at 10 46 41 am" src="https://user-images.githubusercontent.com/4945451/40738251-e8c15740-63f7-11e8-9216-5764a1778388.png">

<hr>

**Examples**

<img width="771" alt="screen shot 2018-05-30 at 10 48 44 am" src="https://user-images.githubusercontent.com/4945451/40738305-10621500-63f8-11e8-8187-5ea97ca9c71f.png">

<img width="1067" alt="screen shot 2018-05-30 at 10 49 51 am" src="https://user-images.githubusercontent.com/4945451/40738322-1efb30ec-63f8-11e8-9ae7-083fee4e9c43.png">

<img width="406" alt="screen shot 2018-05-30 at 10 47 52 am" src="https://user-images.githubusercontent.com/4945451/40738329-230fecf4-63f8-11e8-9e14-522bf1fb6821.png">

**Comment by msurguy** [comment]
@gohai I will look into this soon. Pretty cool feature of Hugo's markdown processor is that we can put plain HTML into markdown and it will remain as HTML, this way we can try using Kube's button classes to make pretty buttons of any sizes: https://imperavi.com/kube/docs/buttons/ 

So, putting `<a href="#" class="button big" role="button">Link</a>` anywhere in markdown documents should work!

**Comment by gohai** [comment]
@msurguy Yeah, the ability to do inline-html has always been a part of Markdown. But I would only look to it as a last resort - a much cleaner alternative would be to make this a regular link, but decorate it via CSS.

**Comment by msurguy** [comment]
@gohai This issue has been addressed via https://github.com/processing/processing-pi-website/pull/6

**Comment by gohai** [comment]
Like what you came up with - thanks!
