### ISSUE TITLE
pi.processing.org returning an error

### ISSUE THREAD

**Issue by lonnen** [processing/processing-pi-website#45]
👋 

CloudFront is reporting a 403 error when I request http://pi.processing.org, and an SSL handshake error when I request https://pi.processing.org/

It is linked from the processing foundation header, and the processing py header, and probably other places

**Comment by benfry** [comment]
Sorry about that… I was in the midst of carefully splitting the Foundation and non-Foundation servers that I was maintaining, and someone from the Foundation flipped out and deleted my accounts and froze some others, causing a nasty DNS disruption. 

It should be fixed now, but may take a little bit for the DNS records to propagate. Thanks for the heads up.

**Comment by lonnen** [comment]
Hey, no problem. Confirmed working!

I'm gonna file one more issue to correct my info on the contributors page and maybe shoot you an email if your old address still works
