### ISSUE TITLE
[Theme] Add Shortcodes for alerts / notifications

### ISSUE THREAD

**Issue by msurguy** [processing/processing-pi-website#5]
Need to create a shortcode and CSS for four different types of notifications within text:
- Danger
- Note
- Information
- Tip

@gohai any others you think would be nice to have?

**Comment by msurguy** [comment]
Inspiration from Apple.com, readthedocs, Bootstrap and others. 

Examples: 

<img width="405" alt="screen shot 2018-05-30 at 2 48 55 pm" src="https://user-images.githubusercontent.com/585833/40749366-a04bfa08-6418-11e8-919b-b74e8fdac658.png">
<img width="395" alt="screen shot 2018-05-30 at 2 48 50 pm" src="https://user-images.githubusercontent.com/585833/40749367-a05f7506-6418-11e8-8760-801144ca2d05.png">
<img width="777" alt="screen shot 2018-05-30 at 2 54 45 pm" src="https://user-images.githubusercontent.com/585833/40749629-7f6d0a9c-6419-11e8-9165-b4c1132f4a4f.png">
<img width="822" alt="screen shot 2018-05-30 at 2 50 55 pm" src="https://user-images.githubusercontent.com/585833/40749630-7f84f15c-6419-11e8-99a8-6059097789e4.png">

**Comment by gohai** [comment]
The bar at the side looks more elegant to me than at the top. Since I could see a fair number of them appearing in places, I believe that a background-color on the light side could be preferable. (Don't think we'd need more than the ones you listed.)

**Comment by msurguy** [comment]
@gohai I've created a separate branch for this but somehow it got pushed to the master directly. I will fix the tracking / pushing issue and will do PRs from now on. Anyway, the Alerts / Messages can now be used and here's what they look like:

![shortcodes processing for pi](https://user-images.githubusercontent.com/585833/40869853-4be020dc-65d7-11e8-8cea-982b7b7cbe49.png)

Feel free to use /post/shortcodes.md as a reference for now

**Comment by msurguy** [comment]
@gohai if you're ok with the style and shortcode for the alerts and notifications, please close this issue
